"""add station_type to station

Revision ID: 43bc0c161286
Revises: 1ef8fb6000a8
Create Date: 2025-05-01 01:27:40.988364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '43bc0c161286'
down_revision = '1ef8fb6000a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts_id', sa.BigInteger(), nullable=False),
    sa.Column('station_id', sa.String(length=64), nullable=False),
    sa.Column('parametertype_name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('parameter_fullname', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ),
    sa.ForeignKeyConstraint(['ts_id'], ['timeseries_metadata.ts_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_series_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_series_data_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_series_data_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_series_data_ts_id'), ['ts_id'], unique=False)

    with op.batch_alter_table('timeseries_data', schema=None) as batch_op:
        batch_op.drop_index('ix_timeseries_data_timestamp')

    op.drop_table('timeseries_data')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('station_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('timeseries_metadata', schema=None) as batch_op:
        batch_op.alter_column('ts_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_index(batch_op.f('ix_timeseries_metadata_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeseries_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeseries_metadata_station_id'))
        batch_op.alter_column('ts_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('station_type')

    op.create_table('timeseries_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('ts_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parametertype_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parameter_fullname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], name='timeseries_data_station_id_fkey'),
    sa.ForeignKeyConstraint(['ts_id'], ['timeseries_metadata.ts_id'], name='timeseries_data_ts_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='timeseries_data_pkey')
    )
    with op.batch_alter_table('timeseries_data', schema=None) as batch_op:
        batch_op.create_index('ix_timeseries_data_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('time_series_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_series_data_ts_id'))
        batch_op.drop_index(batch_op.f('ix_time_series_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_time_series_data_station_id'))

    op.drop_table('time_series_data')
    # ### end Alembic commands ###
