"""add TimeSeriesData

Revision ID: d16cbf37ad54
Revises: 
Create Date: 2025-04-24 22:18:57.722034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd16cbf37ad54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', mysql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('ts_id', sa.BigInteger(), nullable=False),
    sa.Column('parameter_type_name', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('parameter_fullname', sa.Text(), nullable=False),
    sa.Column('station_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_series_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_series_data_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_series_data_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_series_data_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_series_data_ts_id'), ['ts_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_series_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_series_data_ts_id'))
        batch_op.drop_index(batch_op.f('ix_time_series_data_timestamp'))
        batch_op.drop_index(batch_op.f('ix_time_series_data_station_id'))
        batch_op.drop_index(batch_op.f('ix_time_series_data_id'))

    op.drop_table('time_series_data')
    # ### end Alembic commands ###
